2018-08-25 19:19:27,192 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6MiwiZXhwIjoxNTM1MTk2NTQ5LjIyODE1Mzd9.zXOhLZFxLoJ7x1K_EJwc-FfBqZNeXl7hYu72JWgRxd4 [POST] [in /home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lu2905363/PycharmProjects/flask/app/routes.py", line 174, in reset_password
    return redirect(url_for('/reset_password/<token>'))
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint '/reset_password/<token>'. Did you mean 'reset_password' instead?
2018-08-25 19:20:21,147 INFO: Microblog startup [in /home/lu2905363/PycharmProjects/flask/app/__init__.py:48]
2018-08-25 19:21:09,805 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6MiwiZXhwIjoxNTM1MTk2NTQ5LjIyODE1Mzd9.zXOhLZFxLoJ7x1K_EJwc-FfBqZNeXl7hYu72JWgRxd4 [POST] [in /home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lu2905363/PycharmProjects/flask/app/routes.py", line 174, in reset_password
    return redirect(url_for('/reset_password'))
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint '/reset_password'. Did you mean 'reset_password' instead?
2018-08-25 19:21:37,435 INFO: Microblog startup [in /home/lu2905363/PycharmProjects/flask/app/__init__.py:48]
2018-08-25 19:21:54,622 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6MiwiZXhwIjoxNTM1MTk2NTQ5LjIyODE1Mzd9.zXOhLZFxLoJ7x1K_EJwc-FfBqZNeXl7hYu72JWgRxd4 [POST] [in /home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lu2905363/PycharmProjects/flask/app/routes.py", line 174, in reset_password
    return redirect(url_for('reset_password'))
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password'. Did you forget to specify values ['token']?
2018-08-25 19:23:44,161 INFO: Microblog startup [in /home/lu2905363/PycharmProjects/flask/app/__init__.py:48]
2018-08-25 19:25:34,614 INFO: Microblog startup [in /home/lu2905363/PycharmProjects/flask/app/__init__.py:48]
2018-08-25 19:27:03,357 INFO: Microblog startup [in /home/lu2905363/PycharmProjects/flask/app/__init__.py:48]
2018-08-25 19:40:43,855 INFO: Microblog startup [in /home/lu2905363/PycharmProjects/flask/app/__init__.py:48]
2018-08-25 19:46:53,113 INFO: Microblog startup [in /home/lu2905363/PycharmProjects/flask/app/__init__.py:50]
2018-08-25 19:47:34,420 INFO: Microblog startup [in /home/lu2905363/PycharmProjects/flask/app/__init__.py:50]
2018-08-25 19:49:12,450 INFO: Microblog startup [in /home/lu2905363/PycharmProjects/flask/app/__init__.py:50]
2018-08-25 20:03:42,649 INFO: Microblog startup [in /home/lu2905363/PycharmProjects/flask/app/__init__.py:50]
